<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class TesteInd2TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('metas_hist')->insert([
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 1,
                'vlr_meta' => 1124038,
                'vlr_real' => 1905760,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 2,
                'vlr_meta' => 1070512,
                'vlr_real' => 1310573,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 3,
                'vlr_meta' => 1177563,
                'vlr_real' => 1698941,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 4,
                'vlr_meta' => 1070512,
                'vlr_real' => 1501256,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 5,
                'vlr_meta' => 1177563,
                'vlr_real' => 1951666,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 6,
                'vlr_meta' => 1177563,
                'vlr_real' => 1577669,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 7,
                'vlr_meta' => 1124038,
                'vlr_real' => 1615111,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 8,
                'vlr_meta' => 1177563,
                'vlr_real' => 1938516,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 9,
                'vlr_meta' => 1124038,
                'vlr_real' => 1980837,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 10,
                'vlr_meta' => 1177563,
                'vlr_real' => 2082921,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 11,
                'vlr_meta' => 1124038,
                'vlr_real' => 1808674,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 1,
                'ano_id' => 4,
                'mes_id' => 12,
                'vlr_meta' => 1124038,
                'vlr_real' => 1958810,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 1,
                'vlr_meta' => 89.48,
                'vlr_real' => 85.62,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 2,
                'vlr_meta' => 89.77,
                'vlr_real' => 85.75,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 3,
                'vlr_meta' => 88.30,
                'vlr_real' => 87.31,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 4,
                'vlr_meta' => 88.00,
                'vlr_real' => 87.26,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 5,
                'vlr_meta' => 88.76,
                'vlr_real' => 87.83,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 6,
                'vlr_meta' => 89.79,
                'vlr_real' => 88.26,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 7,
                'vlr_meta' => 90.01,
                'vlr_real' => 88.47,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 8,
                'vlr_meta' => 91.05,
                'vlr_real' => 88.47,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 9,
                'vlr_meta' => 92.62,
                'vlr_real' => 90.20,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 10,
                'vlr_meta' => 93.28,
                'vlr_real' => 93.81,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 11,
                'vlr_meta' => 93.85,
                'vlr_real' => 89.02,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['meta_id' => 2,
                'ano_id' => 4,
                'mes_id' => 12,
                'vlr_meta' => 93.96,
                'vlr_real' => 92.42,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]
        ]);
    }
}
